---
version: 2.1
orbs:
  slack: circleci/slack@4.13.3
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1
jobs:
  ensure_formatting:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: install test-dependencies
          command: pip3 install -r test-requirements.txt --user
      - run:
          name: confirm black version
          command: black --version
      - run:
          name: run isort check
          command: isort --check-only .
      - run:
          name: run black check
          command: black --check .
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
  linter:
    docker:
      - image: alpine/flake8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: flake8
          command: flake8 --ignore=E,W ~/repo
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
  build-container:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build opencti/python-client
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install all
            CIRCLE_TAG=${CIRCLE_TAG:-nightly}
            echo "CIRCLE_TAG=${CIRCLE_TAG}"
            BASE_REPO="renizmy"
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker buildx create --use --name mybuilder || true
            docker buildx inspect mybuilder --bootstrap            
            docker buildx build . \
              --platform linux/amd64,linux/arm64 \
              -t $BASE_REPO/client-python:${CIRCLE_TAG} \
              -t $BASE_REPO/client-python:latest \
              --push
  build-library:
    working_directory: ~/opencti-client
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: >
            pip3 install --user -r requirements.txt -r test-requirements.txt
      - run:
          name: check version
          command: |
            package_version="$(
                python3 -c 'import pycti; print(pycti.__version__)'
            )"
            [ "${CIRCLE_TAG}" = "${package_version}" ] \
              || printf "Version mismatch: %s is not equal to %s\n" \
                 "${CIRCLE_TAG}" "${package_version}"
      - run:
          name: build
          command: >
            SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct)" python3 -m build
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/opencti-client
          paths:
            - dist
  deploy:
    working_directory: ~/opencti-client
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - attach_workspace:
          at: ~/opencti-client
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: install twine
          command: pip3 install twine
      - run:
          name: init .pypirc
          command: >
            printf "[pypi]\nusername = __token__\npassword = %s\n"
            "${PYPI_PASSWORD}" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: twine upload dist/*
      - slack/notify:
          branch_pattern: master
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
  notify_rolling:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
      - ms-teams/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
      - ms-teams/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL

workflows:
  version: 2
  opencti_client_python:
    jobs:
      - ensure_formatting:
          filters:
            tags:
              only: /.*/
      - linter:
          filters:
            tags:
              only: /.*/
      - build-container:
          filters:
            tags:
              only: /.*/
      - build-library:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)?\.?(\w)*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build-library
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)?\.?(\w)*/
            branches:
              ignore: /.*/
      - notify_rolling:
          requires:
            - build-library
      - notify:
          requires:
            - deploy
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)?\.?(\w)*/
            branches:
              ignore: /.*/
